spring:
  application:
    name: millkbot

  main:
    banner-mode: "off"

  profiles:
    active: prod

logging:
  level:
    com.bigboss.millkbot: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG

prompt:
  path: "file:./system_prompt"

jimmer:
  language: kotlin
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
